swagger: '2.0'
basePath: /v1
info:
  version: 1.0.0
  title: Dentist Selection
  description: Book an appointment with a dentist
  contact:
    name: Tim Chen
    email: tianpeng.chen@student.unsw.edu.au
paths:
  /dentist:
    get:
      summary: To get all available dentist
      tags:
        - Dentists
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
                description: message from server
              dentist:
                type: array
                items:
                  $ref: '#/definitions/Dentist'
                description: array of all dentist
                
  /dentist/{id}:
    get:
      summary: To get information of a dentist
      tags:
        - Dentists
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          minimum: 0
          description: ID of the dentist
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              Dentist:
                $ref: '#/definitions/Dentist'
        '404':
          description: Dentist not found on server.
          schema:
            type: object
            properties:
              message:
                type: string
                description: Dentist not found on server.
  
  /dentist/{id}/timeslosts:
    get:
      summary: To get all available timeslots of a dentist
      tags:
        - Dentists
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          minimum: 0
          description: ID of the dentist
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              timeslots:
                type: array
                items:
                  type: object
        '404':
          description: Dentist not found on server.
          schema:
            type: object
            properties:
              message:
                type: string
                example: Dentist not found on server.
                description: message from server

definitions:
  Dentist:
    properties:
      id:
        type: integer
        example: 2
        description: the dentist ID.
      name:
        type: string
        example: "Dr. John"
        description: the dentist name.
      location:
        type: string
        example: "Kingsford"
        description: the dentist location.
      specialization:
        type: string
        enum:
          - "Paediatric Dentistry"
          - "Orthodontics"
          - "Oral Surgery"
    required:
      - id
      - name
      - location
      - specialization